import { writeJsonFile } from "../persistence/json-db";
import { readybotPlaybookForAgent } from "@/lib/platform/playbooks/digital-ready-readybot";
import { buildReadybotKnowledgeEntries } from "@/lib/platform/seed/readybot-knowledge";
import type {
  Agent,
  AgentTask,
  Booking,
  Campaign,
  Conversation,
  Integration,
  KnowledgeBase,
  KnowledgeEntry,
  Lead,
  Message,
  Organization,
  Profile,
} from "./types";

const ORG_ID = "org-drg-001";
const PROFILE_ID = "prof-001";

export async function seedPlatformData(): Promise<void> {
  const now = new Date().toISOString();

  const org: Organization = {
    id: ORG_ID,
    name: "Digital Ready Ghana",
    industry: "Digital Marketing & Technology",
    website: "https://digitalreadyghana.com",
    email: "hello@digitalreadyghana.com",
    phone: "+233 30 000 0000",
    timezone: "Africa/Accra",
    created_at: now,
  };

  const profile: Profile = {
    id: PROFILE_ID,
    user_id: "demo-user-0001",
    organization_id: ORG_ID,
    full_name: "Platform Admin",
    role: "company_admin",
    department: "Management",
    status: "active",
    created_at: now,
  };

  const agents: Agent[] = [
    {
      id: "agent-sales-001",
      organization_id: ORG_ID,
      ...readybotPlaybookForAgent(),
      position: "Lead Qualification — BDR",
      timezone: "Africa/Accra",
      voice: "alloy",
      voice_speed: 1,
      channels: ["website", "whatsapp", "live_agent", "embed"],
      status: "active",
      enabled: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "agent-support-001",
      organization_id: ORG_ID,
      name: "Customer Support Assistant",
      nickname: "Ama",
      company_product_name: "Digital Ready Ghana",
      agent_type: "support",
      position: "Support Specialist",
      language: "en",
      tone: "friendly",
      timezone: "Africa/Accra",
      welcome_message: "Hello! I'm Ama. How can I help with your account or services today?",
      system_prompt:
        "You are a helpful customer support agent for Digital Ready Ghana. Resolve issues, explain processes, and escalate complex cases.",
      channels: ["website"],
      status: "active",
      enabled: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: "agent-booking-001",
      organization_id: ORG_ID,
      name: "Appointment Booking Assistant",
      nickname: "Esi",
      company_product_name: "Digital Ready Ghana",
      agent_type: "booking",
      position: "Scheduling Coordinator",
      language: "en",
      tone: "professional",
      timezone: "Africa/Accra",
      welcome_message: "I can help you schedule a consultation with our team. What service are you interested in?",
      system_prompt:
        "You help customers book meetings. Collect name, email, phone, preferred date/time, and service needed.",
      channels: ["website", "phone"],
      status: "active",
      enabled: true,
      created_at: now,
      updated_at: now,
    },
  ];

  const kbId = "kb-main-001";
  const knowledgeBases: KnowledgeBase[] = [
    {
      id: kbId,
      organization_id: ORG_ID,
      title: "Digital Ready Ghana — Master KB",
      description: "Company profile, services, pricing, FAQs",
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];

  const knowledgeEntries: KnowledgeEntry[] = buildReadybotKnowledgeEntries({
    knowledgeBaseId: kbId,
    organizationId: ORG_ID,
    now,
  });

  const leads: Lead[] = [
    {
      id: "lead-001",
      organization_id: ORG_ID,
      full_name: "Kwame Mensah",
      phone: "+233 24 111 2233",
      email: "kwame@acmecorp.gh",
      business_name: "Acme Corp Ghana",
      service_interest: "Social Media Management",
      budget: "GHS 3,000–5,000/month",
      timeline: "Within 30 days",
      source: "website",
      lead_score: 82,
      lead_category: "hot",
      lead_status: "qualified",
      summary: "Wants full social management for retail brand.",
      next_action: "Send proposal",
      follow_up_date: new Date(Date.now() + 86400000).toISOString(),
      created_at: now,
      updated_at: now,
    },
    {
      id: "lead-002",
      organization_id: ORG_ID,
      full_name: "Ama Osei",
      email: "ama.osei@startup.io",
      service_interest: "Website Development",
      lead_score: 55,
      lead_category: "warm",
      lead_status: "working",
      source: "website",
      created_at: now,
      updated_at: now,
    },
    {
      id: "lead-003",
      organization_id: ORG_ID,
      full_name: "John Boateng",
      phone: "+233 55 999 8877",
      service_interest: "SEO",
      lead_score: 40,
      lead_category: "cold",
      lead_status: "open",
      source: "whatsapp",
      created_at: now,
      updated_at: now,
    },
    {
      id: "lead-004",
      organization_id: ORG_ID,
      full_name: "Sarah Addo",
      business_name: "Addo Boutique",
      service_interest: "Digital Advertising",
      budget: "GHS 2,000",
      lead_score: 70,
      lead_category: "warm",
      lead_status: "working",
      source: "website",
      created_at: now,
      updated_at: now,
    },
    {
      id: "lead-005",
      organization_id: ORG_ID,
      full_name: "Michael Tetteh",
      service_interest: "Branding",
      lead_score: 90,
      lead_category: "hot",
      lead_status: "opportunity_created",
      source: "referral",
      created_at: now,
      updated_at: now,
    },
    {
      id: "lead-006",
      organization_id: ORG_ID,
      full_name: "Guest User",
      service_interest: "Support",
      lead_category: "support",
      lead_status: "open",
      lead_score: 20,
      source: "website",
      created_at: now,
      updated_at: now,
    },
    {
      id: "lead-007",
      organization_id: ORG_ID,
      full_name: "Efua Darko",
      service_interest: "Content Creation",
      lead_score: 48,
      lead_category: "warm",
      lead_status: "created",
      source: "website",
      created_at: now,
      updated_at: now,
    },
    {
      id: "lead-008",
      organization_id: ORG_ID,
      full_name: "Daniel K.",
      service_interest: "Motion Graphics",
      lead_score: 35,
      lead_category: "cold",
      lead_status: "disqualified",
      source: "website",
      created_at: now,
      updated_at: now,
    },
    {
      id: "lead-009",
      organization_id: ORG_ID,
      full_name: "Grace N.",
      service_interest: "Marketing Consultation",
      lead_score: 75,
      lead_category: "hot",
      lead_status: "qualified",
      source: "website",
      created_at: now,
      updated_at: now,
    },
    {
      id: "lead-010",
      organization_id: ORG_ID,
      full_name: "Prince A.",
      service_interest: "Website Development",
      lead_score: 60,
      lead_category: "warm",
      lead_status: "customer",
      source: "website",
      created_at: now,
      updated_at: now,
    },
  ];

  const convId = "conv-001";
  const conversations: Conversation[] = [
    {
      id: convId,
      organization_id: ORG_ID,
      agent_id: "agent-sales-001",
      lead_id: "lead-001",
      customer_name: "Kwame Mensah",
      customer_email: "kwame@acmecorp.gh",
      channel: "website",
      status: "human_needed",
      detected_intent: "sales_enquiry",
      ai_confidence: 0.88,
      summary: "Interested in social media management for retail. Asked about pricing.",
      recommended_next_action: "Sales rep call within 2 hours",
      created_at: now,
      updated_at: now,
    },
    {
      id: "conv-002",
      organization_id: ORG_ID,
      agent_id: "agent-sales-001",
      customer_name: "Visitor",
      channel: "website",
      status: "ai_handling",
      detected_intent: "general",
      ai_confidence: 0.72,
      created_at: now,
      updated_at: now,
    },
    {
      id: "conv-003",
      organization_id: ORG_ID,
      agent_id: "agent-support-001",
      customer_name: "Ama Osei",
      channel: "whatsapp",
      status: "resolved",
      ai_confidence: 0.91,
      created_at: now,
      updated_at: now,
    },
    {
      id: "conv-004",
      organization_id: ORG_ID,
      agent_id: "agent-booking-001",
      lead_id: "lead-005",
      customer_name: "Michael Tetteh",
      channel: "website",
      status: "booked",
      ai_confidence: 0.95,
      created_at: now,
      updated_at: now,
    },
    {
      id: "conv-005",
      organization_id: ORG_ID,
      agent_id: "agent-sales-001",
      channel: "website",
      status: "new",
      created_at: now,
      updated_at: now,
    },
    {
      id: "conv-006",
      organization_id: ORG_ID,
      agent_id: "agent-support-001",
      status: "follow_up",
      channel: "website",
      created_at: now,
      updated_at: now,
    },
    {
      id: "conv-007",
      organization_id: ORG_ID,
      agent_id: "agent-sales-001",
      status: "closed",
      channel: "phone",
      created_at: now,
      updated_at: now,
    },
    {
      id: "conv-008",
      organization_id: ORG_ID,
      agent_id: "agent-booking-001",
      status: "waiting_customer",
      channel: "website",
      created_at: now,
      updated_at: now,
    },
  ];

  const messages: Message[] = [
    {
      id: "msg-1",
      conversation_id: convId,
      sender_type: "user",
      content: "I need social media management for my business.",
      created_at: now,
    },
    {
      id: "msg-2",
      conversation_id: convId,
      sender_type: "assistant",
      sender_name: "Kofi",
      content:
        "Great choice! Social media management is one of our core services. What type of business do you run, and which platforms are you most active on?",
      created_at: now,
    },
    {
      id: "msg-3",
      conversation_id: convId,
      sender_type: "user",
      content: "Retail — mostly Instagram and Facebook. What's your pricing?",
      created_at: now,
    },
    {
      id: "msg-4",
      conversation_id: convId,
      sender_type: "assistant",
      sender_name: "Kofi",
      content:
        "Pricing is tailored to your posting frequency and platforms. I'd recommend a quick discovery call so we can quote accurately. Would you like me to book that for you?",
      created_at: now,
    },
  ];

  const bookings: Booking[] = [
    {
      id: "book-001",
      organization_id: ORG_ID,
      agent_id: "agent-booking-001",
      lead_id: "lead-005",
      title: "Branding Discovery Call",
      customer_name: "Michael Tetteh",
      service_needed: "Branding",
      meeting_date: "2026-05-20",
      meeting_time: "10:00:00",
      duration_minutes: 30,
      status: "confirmed",
      meeting_link: "https://meet.example.com/branding",
      created_at: now,
      updated_at: now,
    },
    {
      id: "book-002",
      organization_id: ORG_ID,
      title: "Social Media Consultation",
      customer_name: "Kwame Mensah",
      customer_email: "kwame@acmecorp.gh",
      service_needed: "Social Media Management",
      meeting_date: "2026-05-18",
      meeting_time: "14:00:00",
      duration_minutes: 45,
      status: "scheduled",
      created_at: now,
      updated_at: now,
    },
    {
      id: "book-003",
      organization_id: ORG_ID,
      title: "SEO Audit Review",
      customer_name: "John Boateng",
      service_needed: "SEO",
      meeting_date: "2026-05-22",
      meeting_time: "11:00:00",
      status: "scheduled",
      created_at: now,
      updated_at: now,
    },
    {
      id: "book-004",
      organization_id: ORG_ID,
      title: "Website Kickoff",
      customer_name: "Ama Osei",
      service_needed: "Website Development",
      status: "completed",
      created_at: now,
      updated_at: now,
    },
    {
      id: "book-005",
      organization_id: ORG_ID,
      title: "Ads Strategy Session",
      customer_name: "Sarah Addo",
      service_needed: "Digital Advertising",
      status: "missed",
      created_at: now,
      updated_at: now,
    },
  ];

  const campaigns: Campaign[] = [
    {
      id: "camp-001",
      organization_id: ORG_ID,
      agent_id: "agent-sales-001",
      name: "Warm Lead Follow-up — May",
      campaign_type: "follow_up",
      status: "live",
      scheduled_at: now,
      created_at: now,
      updated_at: now,
    },
    {
      id: "camp-002",
      organization_id: ORG_ID,
      agent_id: "agent-sales-001",
      name: "Re-engage Cold Leads",
      campaign_type: "outbound",
      status: "draft",
      created_at: now,
      updated_at: now,
    },
  ];

  const agentTasks: AgentTask[] = [
    {
      id: "task-001",
      organization_id: ORG_ID,
      agent_id: "agent-sales-001",
      name: "Hot Lead Slack Alert",
      trigger_type: "lead_hot",
      action_type: "notify_team",
      webhook_url: process.env.ESCALATION_SLACK_WEBHOOK ?? "",
      http_method: "POST",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "task-002",
      organization_id: ORG_ID,
      agent_id: "agent-sales-001",
      name: "CRM on Qualified Lead",
      trigger_type: "lead_qualified",
      action_type: "create_crm_record",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "task-003",
      organization_id: ORG_ID,
      agent_id: "agent-support-001",
      name: "Human Handoff Email",
      trigger_type: "human_requested",
      action_type: "send_email",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "task-004",
      organization_id: ORG_ID,
      agent_id: "agent-booking-001",
      name: "Meeting Booked Webhook",
      trigger_type: "meeting_booked",
      action_type: "send_webhook",
      webhook_url: "https://hooks.example.com/meeting",
      http_method: "POST",
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];

  const integrations: Integration[] = [
    { id: "int-1", organization_id: ORG_ID, integration_type: "openai", status: "connected", created_at: now, updated_at: now },
    { id: "int-2", organization_id: ORG_ID, integration_type: "whatsapp", status: "not_connected", created_at: now, updated_at: now },
    { id: "int-voice", organization_id: ORG_ID, integration_type: "twilio_voice", status: "not_connected", created_at: now, updated_at: now },
    { id: "int-3", organization_id: ORG_ID, integration_type: "google_calendar", status: "needs_attention", created_at: now, updated_at: now },
    { id: "int-4", organization_id: ORG_ID, integration_type: "hubspot", status: "not_connected", created_at: now, updated_at: now },
    { id: "int-5", organization_id: ORG_ID, integration_type: "website_chat", status: "connected", created_at: now, updated_at: now },
  ];

  await writeJsonFile("platform/organization.json", org);
  await writeJsonFile("platform/profiles.json", [profile]);
  await writeJsonFile("platform/agents.json", agents);
  await writeJsonFile("platform/knowledge-bases.json", knowledgeBases);
  await writeJsonFile("platform/knowledge-entries.json", knowledgeEntries);
  await writeJsonFile("platform/agent-knowledge.json", [
    { id: "akb-1", agent_id: "agent-sales-001", knowledge_base_id: kbId, created_at: now },
    { id: "akb-2", agent_id: "agent-support-001", knowledge_base_id: kbId, created_at: now },
  ]);
  await writeJsonFile("platform/leads.json", leads);
  await writeJsonFile("platform/conversations.json", conversations);
  await writeJsonFile("platform/messages.json", messages);
  await writeJsonFile("platform/bookings.json", bookings);
  await writeJsonFile("platform/campaigns.json", campaigns);
  await writeJsonFile("platform/agent-tasks.json", agentTasks);
  await writeJsonFile("platform/integrations.json", integrations);
  await writeJsonFile("platform/notifications.json", [
    {
      id: "notif-1",
      organization_id: ORG_ID,
      type: "handoff",
      title: "Human handoff required",
      message: "Kwame Mensah conversation needs a sales rep.",
      status: "unread",
      created_at: now,
    },
  ]);
}
